# Generated by Django 2.2.18 on 2021-11-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0003_auto_20211116_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='image',
            field=models.ImageField(blank=True, height_field=100, max_length=500, upload_to='concerts_images', width_field=100),
        ),
    ]
